/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InquilinoRouteImport } from './routes/inquilino'
import { Route as DonoRouteImport } from './routes/dono'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InquilinoVisaoGeralRouteImport } from './routes/inquilino.visao-geral'
import { Route as InquilinoProximidadesRouteImport } from './routes/inquilino.proximidades'
import { Route as InquilinoMeuImovelRouteImport } from './routes/inquilino.meu-imovel'
import { Route as InquilinoManutencaoRouteImport } from './routes/inquilino.manutencao'
import { Route as InquilinoFinanceiroRouteImport } from './routes/inquilino.financeiro'
import { Route as InquilinoDocumentosRouteImport } from './routes/inquilino.documentos'
import { Route as InquilinoConversasRouteImport } from './routes/inquilino.conversas'
import { Route as InquilinoContratoRouteImport } from './routes/inquilino.contrato'
import { Route as DonoVisaoGeralRouteImport } from './routes/dono.visao-geral'
import { Route as DonoPagamentosRouteImport } from './routes/dono.pagamentos'
import { Route as DonoMapaRouteImport } from './routes/dono.mapa'
import { Route as DonoManutencaoRouteImport } from './routes/dono.manutencao'
import { Route as DonoImoveisRouteImport } from './routes/dono.imoveis'
import { Route as DonoFinanceiroRouteImport } from './routes/dono.financeiro'
import { Route as DonoDocumentosRouteImport } from './routes/dono.documentos'
import { Route as DonoConversasRouteImport } from './routes/dono.conversas'
import { Route as DonoContratosRouteImport } from './routes/dono.contratos'
import { Route as DonoBlockchainRouteImport } from './routes/dono.blockchain'
import { Route as DonoAdministracaoRouteImport } from './routes/dono.administracao'
import { Route as DonoAcessosRouteImport } from './routes/dono.acessos'
import { Route as DonoImoveisIndexRouteImport } from './routes/dono.imoveis.index'
import { Route as DonoImoveisIdRouteImport } from './routes/dono.imoveis.$id'

const InquilinoRoute = InquilinoRouteImport.update({
  id: '/inquilino',
  path: '/inquilino',
  getParentRoute: () => rootRouteImport,
} as any)
const DonoRoute = DonoRouteImport.update({
  id: '/dono',
  path: '/dono',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InquilinoVisaoGeralRoute = InquilinoVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => InquilinoRoute,
} as any)
const InquilinoProximidadesRoute = InquilinoProximidadesRouteImport.update({
  id: '/proximidades',
  path: '/proximidades',
  getParentRoute: () => InquilinoRoute,
} as any)
const InquilinoMeuImovelRoute = InquilinoMeuImovelRouteImport.update({
  id: '/meu-imovel',
  path: '/meu-imovel',
  getParentRoute: () => InquilinoRoute,
} as any)
const InquilinoManutencaoRoute = InquilinoManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => InquilinoRoute,
} as any)
const InquilinoFinanceiroRoute = InquilinoFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => InquilinoRoute,
} as any)
const InquilinoDocumentosRoute = InquilinoDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => InquilinoRoute,
} as any)
const InquilinoConversasRoute = InquilinoConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => InquilinoRoute,
} as any)
const InquilinoContratoRoute = InquilinoContratoRouteImport.update({
  id: '/contrato',
  path: '/contrato',
  getParentRoute: () => InquilinoRoute,
} as any)
const DonoVisaoGeralRoute = DonoVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => DonoRoute,
} as any)
const DonoPagamentosRoute = DonoPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => DonoRoute,
} as any)
const DonoMapaRoute = DonoMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => DonoRoute,
} as any)
const DonoManutencaoRoute = DonoManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => DonoRoute,
} as any)
const DonoImoveisRoute = DonoImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => DonoRoute,
} as any)
const DonoFinanceiroRoute = DonoFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => DonoRoute,
} as any)
const DonoDocumentosRoute = DonoDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => DonoRoute,
} as any)
const DonoConversasRoute = DonoConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => DonoRoute,
} as any)
const DonoContratosRoute = DonoContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => DonoRoute,
} as any)
const DonoBlockchainRoute = DonoBlockchainRouteImport.update({
  id: '/blockchain',
  path: '/blockchain',
  getParentRoute: () => DonoRoute,
} as any)
const DonoAdministracaoRoute = DonoAdministracaoRouteImport.update({
  id: '/administracao',
  path: '/administracao',
  getParentRoute: () => DonoRoute,
} as any)
const DonoAcessosRoute = DonoAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => DonoRoute,
} as any)
const DonoImoveisIndexRoute = DonoImoveisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DonoImoveisRoute,
} as any)
const DonoImoveisIdRoute = DonoImoveisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DonoImoveisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dono': typeof DonoRouteWithChildren
  '/inquilino': typeof InquilinoRouteWithChildren
  '/dono/acessos': typeof DonoAcessosRoute
  '/dono/administracao': typeof DonoAdministracaoRoute
  '/dono/blockchain': typeof DonoBlockchainRoute
  '/dono/contratos': typeof DonoContratosRoute
  '/dono/conversas': typeof DonoConversasRoute
  '/dono/documentos': typeof DonoDocumentosRoute
  '/dono/financeiro': typeof DonoFinanceiroRoute
  '/dono/imoveis': typeof DonoImoveisRouteWithChildren
  '/dono/manutencao': typeof DonoManutencaoRoute
  '/dono/mapa': typeof DonoMapaRoute
  '/dono/pagamentos': typeof DonoPagamentosRoute
  '/dono/visao-geral': typeof DonoVisaoGeralRoute
  '/inquilino/contrato': typeof InquilinoContratoRoute
  '/inquilino/conversas': typeof InquilinoConversasRoute
  '/inquilino/documentos': typeof InquilinoDocumentosRoute
  '/inquilino/financeiro': typeof InquilinoFinanceiroRoute
  '/inquilino/manutencao': typeof InquilinoManutencaoRoute
  '/inquilino/meu-imovel': typeof InquilinoMeuImovelRoute
  '/inquilino/proximidades': typeof InquilinoProximidadesRoute
  '/inquilino/visao-geral': typeof InquilinoVisaoGeralRoute
  '/dono/imoveis/$id': typeof DonoImoveisIdRoute
  '/dono/imoveis/': typeof DonoImoveisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dono': typeof DonoRouteWithChildren
  '/inquilino': typeof InquilinoRouteWithChildren
  '/dono/acessos': typeof DonoAcessosRoute
  '/dono/administracao': typeof DonoAdministracaoRoute
  '/dono/blockchain': typeof DonoBlockchainRoute
  '/dono/contratos': typeof DonoContratosRoute
  '/dono/conversas': typeof DonoConversasRoute
  '/dono/documentos': typeof DonoDocumentosRoute
  '/dono/financeiro': typeof DonoFinanceiroRoute
  '/dono/manutencao': typeof DonoManutencaoRoute
  '/dono/mapa': typeof DonoMapaRoute
  '/dono/pagamentos': typeof DonoPagamentosRoute
  '/dono/visao-geral': typeof DonoVisaoGeralRoute
  '/inquilino/contrato': typeof InquilinoContratoRoute
  '/inquilino/conversas': typeof InquilinoConversasRoute
  '/inquilino/documentos': typeof InquilinoDocumentosRoute
  '/inquilino/financeiro': typeof InquilinoFinanceiroRoute
  '/inquilino/manutencao': typeof InquilinoManutencaoRoute
  '/inquilino/meu-imovel': typeof InquilinoMeuImovelRoute
  '/inquilino/proximidades': typeof InquilinoProximidadesRoute
  '/inquilino/visao-geral': typeof InquilinoVisaoGeralRoute
  '/dono/imoveis/$id': typeof DonoImoveisIdRoute
  '/dono/imoveis': typeof DonoImoveisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dono': typeof DonoRouteWithChildren
  '/inquilino': typeof InquilinoRouteWithChildren
  '/dono/acessos': typeof DonoAcessosRoute
  '/dono/administracao': typeof DonoAdministracaoRoute
  '/dono/blockchain': typeof DonoBlockchainRoute
  '/dono/contratos': typeof DonoContratosRoute
  '/dono/conversas': typeof DonoConversasRoute
  '/dono/documentos': typeof DonoDocumentosRoute
  '/dono/financeiro': typeof DonoFinanceiroRoute
  '/dono/imoveis': typeof DonoImoveisRouteWithChildren
  '/dono/manutencao': typeof DonoManutencaoRoute
  '/dono/mapa': typeof DonoMapaRoute
  '/dono/pagamentos': typeof DonoPagamentosRoute
  '/dono/visao-geral': typeof DonoVisaoGeralRoute
  '/inquilino/contrato': typeof InquilinoContratoRoute
  '/inquilino/conversas': typeof InquilinoConversasRoute
  '/inquilino/documentos': typeof InquilinoDocumentosRoute
  '/inquilino/financeiro': typeof InquilinoFinanceiroRoute
  '/inquilino/manutencao': typeof InquilinoManutencaoRoute
  '/inquilino/meu-imovel': typeof InquilinoMeuImovelRoute
  '/inquilino/proximidades': typeof InquilinoProximidadesRoute
  '/inquilino/visao-geral': typeof InquilinoVisaoGeralRoute
  '/dono/imoveis/$id': typeof DonoImoveisIdRoute
  '/dono/imoveis/': typeof DonoImoveisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dono'
    | '/inquilino'
    | '/dono/acessos'
    | '/dono/administracao'
    | '/dono/blockchain'
    | '/dono/contratos'
    | '/dono/conversas'
    | '/dono/documentos'
    | '/dono/financeiro'
    | '/dono/imoveis'
    | '/dono/manutencao'
    | '/dono/mapa'
    | '/dono/pagamentos'
    | '/dono/visao-geral'
    | '/inquilino/contrato'
    | '/inquilino/conversas'
    | '/inquilino/documentos'
    | '/inquilino/financeiro'
    | '/inquilino/manutencao'
    | '/inquilino/meu-imovel'
    | '/inquilino/proximidades'
    | '/inquilino/visao-geral'
    | '/dono/imoveis/$id'
    | '/dono/imoveis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dono'
    | '/inquilino'
    | '/dono/acessos'
    | '/dono/administracao'
    | '/dono/blockchain'
    | '/dono/contratos'
    | '/dono/conversas'
    | '/dono/documentos'
    | '/dono/financeiro'
    | '/dono/manutencao'
    | '/dono/mapa'
    | '/dono/pagamentos'
    | '/dono/visao-geral'
    | '/inquilino/contrato'
    | '/inquilino/conversas'
    | '/inquilino/documentos'
    | '/inquilino/financeiro'
    | '/inquilino/manutencao'
    | '/inquilino/meu-imovel'
    | '/inquilino/proximidades'
    | '/inquilino/visao-geral'
    | '/dono/imoveis/$id'
    | '/dono/imoveis'
  id:
    | '__root__'
    | '/'
    | '/dono'
    | '/inquilino'
    | '/dono/acessos'
    | '/dono/administracao'
    | '/dono/blockchain'
    | '/dono/contratos'
    | '/dono/conversas'
    | '/dono/documentos'
    | '/dono/financeiro'
    | '/dono/imoveis'
    | '/dono/manutencao'
    | '/dono/mapa'
    | '/dono/pagamentos'
    | '/dono/visao-geral'
    | '/inquilino/contrato'
    | '/inquilino/conversas'
    | '/inquilino/documentos'
    | '/inquilino/financeiro'
    | '/inquilino/manutencao'
    | '/inquilino/meu-imovel'
    | '/inquilino/proximidades'
    | '/inquilino/visao-geral'
    | '/dono/imoveis/$id'
    | '/dono/imoveis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DonoRoute: typeof DonoRouteWithChildren
  InquilinoRoute: typeof InquilinoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inquilino': {
      id: '/inquilino'
      path: '/inquilino'
      fullPath: '/inquilino'
      preLoaderRoute: typeof InquilinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dono': {
      id: '/dono'
      path: '/dono'
      fullPath: '/dono'
      preLoaderRoute: typeof DonoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquilino/visao-geral': {
      id: '/inquilino/visao-geral'
      path: '/visao-geral'
      fullPath: '/inquilino/visao-geral'
      preLoaderRoute: typeof InquilinoVisaoGeralRouteImport
      parentRoute: typeof InquilinoRoute
    }
    '/inquilino/proximidades': {
      id: '/inquilino/proximidades'
      path: '/proximidades'
      fullPath: '/inquilino/proximidades'
      preLoaderRoute: typeof InquilinoProximidadesRouteImport
      parentRoute: typeof InquilinoRoute
    }
    '/inquilino/meu-imovel': {
      id: '/inquilino/meu-imovel'
      path: '/meu-imovel'
      fullPath: '/inquilino/meu-imovel'
      preLoaderRoute: typeof InquilinoMeuImovelRouteImport
      parentRoute: typeof InquilinoRoute
    }
    '/inquilino/manutencao': {
      id: '/inquilino/manutencao'
      path: '/manutencao'
      fullPath: '/inquilino/manutencao'
      preLoaderRoute: typeof InquilinoManutencaoRouteImport
      parentRoute: typeof InquilinoRoute
    }
    '/inquilino/financeiro': {
      id: '/inquilino/financeiro'
      path: '/financeiro'
      fullPath: '/inquilino/financeiro'
      preLoaderRoute: typeof InquilinoFinanceiroRouteImport
      parentRoute: typeof InquilinoRoute
    }
    '/inquilino/documentos': {
      id: '/inquilino/documentos'
      path: '/documentos'
      fullPath: '/inquilino/documentos'
      preLoaderRoute: typeof InquilinoDocumentosRouteImport
      parentRoute: typeof InquilinoRoute
    }
    '/inquilino/conversas': {
      id: '/inquilino/conversas'
      path: '/conversas'
      fullPath: '/inquilino/conversas'
      preLoaderRoute: typeof InquilinoConversasRouteImport
      parentRoute: typeof InquilinoRoute
    }
    '/inquilino/contrato': {
      id: '/inquilino/contrato'
      path: '/contrato'
      fullPath: '/inquilino/contrato'
      preLoaderRoute: typeof InquilinoContratoRouteImport
      parentRoute: typeof InquilinoRoute
    }
    '/dono/visao-geral': {
      id: '/dono/visao-geral'
      path: '/visao-geral'
      fullPath: '/dono/visao-geral'
      preLoaderRoute: typeof DonoVisaoGeralRouteImport
      parentRoute: typeof DonoRoute
    }
    '/dono/pagamentos': {
      id: '/dono/pagamentos'
      path: '/pagamentos'
      fullPath: '/dono/pagamentos'
      preLoaderRoute: typeof DonoPagamentosRouteImport
      parentRoute: typeof DonoRoute
    }
    '/dono/mapa': {
      id: '/dono/mapa'
      path: '/mapa'
      fullPath: '/dono/mapa'
      preLoaderRoute: typeof DonoMapaRouteImport
      parentRoute: typeof DonoRoute
    }
    '/dono/manutencao': {
      id: '/dono/manutencao'
      path: '/manutencao'
      fullPath: '/dono/manutencao'
      preLoaderRoute: typeof DonoManutencaoRouteImport
      parentRoute: typeof DonoRoute
    }
    '/dono/imoveis': {
      id: '/dono/imoveis'
      path: '/imoveis'
      fullPath: '/dono/imoveis'
      preLoaderRoute: typeof DonoImoveisRouteImport
      parentRoute: typeof DonoRoute
    }
    '/dono/financeiro': {
      id: '/dono/financeiro'
      path: '/financeiro'
      fullPath: '/dono/financeiro'
      preLoaderRoute: typeof DonoFinanceiroRouteImport
      parentRoute: typeof DonoRoute
    }
    '/dono/documentos': {
      id: '/dono/documentos'
      path: '/documentos'
      fullPath: '/dono/documentos'
      preLoaderRoute: typeof DonoDocumentosRouteImport
      parentRoute: typeof DonoRoute
    }
    '/dono/conversas': {
      id: '/dono/conversas'
      path: '/conversas'
      fullPath: '/dono/conversas'
      preLoaderRoute: typeof DonoConversasRouteImport
      parentRoute: typeof DonoRoute
    }
    '/dono/contratos': {
      id: '/dono/contratos'
      path: '/contratos'
      fullPath: '/dono/contratos'
      preLoaderRoute: typeof DonoContratosRouteImport
      parentRoute: typeof DonoRoute
    }
    '/dono/blockchain': {
      id: '/dono/blockchain'
      path: '/blockchain'
      fullPath: '/dono/blockchain'
      preLoaderRoute: typeof DonoBlockchainRouteImport
      parentRoute: typeof DonoRoute
    }
    '/dono/administracao': {
      id: '/dono/administracao'
      path: '/administracao'
      fullPath: '/dono/administracao'
      preLoaderRoute: typeof DonoAdministracaoRouteImport
      parentRoute: typeof DonoRoute
    }
    '/dono/acessos': {
      id: '/dono/acessos'
      path: '/acessos'
      fullPath: '/dono/acessos'
      preLoaderRoute: typeof DonoAcessosRouteImport
      parentRoute: typeof DonoRoute
    }
    '/dono/imoveis/': {
      id: '/dono/imoveis/'
      path: '/'
      fullPath: '/dono/imoveis/'
      preLoaderRoute: typeof DonoImoveisIndexRouteImport
      parentRoute: typeof DonoImoveisRoute
    }
    '/dono/imoveis/$id': {
      id: '/dono/imoveis/$id'
      path: '/$id'
      fullPath: '/dono/imoveis/$id'
      preLoaderRoute: typeof DonoImoveisIdRouteImport
      parentRoute: typeof DonoImoveisRoute
    }
  }
}

interface DonoImoveisRouteChildren {
  DonoImoveisIdRoute: typeof DonoImoveisIdRoute
  DonoImoveisIndexRoute: typeof DonoImoveisIndexRoute
}

const DonoImoveisRouteChildren: DonoImoveisRouteChildren = {
  DonoImoveisIdRoute: DonoImoveisIdRoute,
  DonoImoveisIndexRoute: DonoImoveisIndexRoute,
}

const DonoImoveisRouteWithChildren = DonoImoveisRoute._addFileChildren(
  DonoImoveisRouteChildren,
)

interface DonoRouteChildren {
  DonoAcessosRoute: typeof DonoAcessosRoute
  DonoAdministracaoRoute: typeof DonoAdministracaoRoute
  DonoBlockchainRoute: typeof DonoBlockchainRoute
  DonoContratosRoute: typeof DonoContratosRoute
  DonoConversasRoute: typeof DonoConversasRoute
  DonoDocumentosRoute: typeof DonoDocumentosRoute
  DonoFinanceiroRoute: typeof DonoFinanceiroRoute
  DonoImoveisRoute: typeof DonoImoveisRouteWithChildren
  DonoManutencaoRoute: typeof DonoManutencaoRoute
  DonoMapaRoute: typeof DonoMapaRoute
  DonoPagamentosRoute: typeof DonoPagamentosRoute
  DonoVisaoGeralRoute: typeof DonoVisaoGeralRoute
}

const DonoRouteChildren: DonoRouteChildren = {
  DonoAcessosRoute: DonoAcessosRoute,
  DonoAdministracaoRoute: DonoAdministracaoRoute,
  DonoBlockchainRoute: DonoBlockchainRoute,
  DonoContratosRoute: DonoContratosRoute,
  DonoConversasRoute: DonoConversasRoute,
  DonoDocumentosRoute: DonoDocumentosRoute,
  DonoFinanceiroRoute: DonoFinanceiroRoute,
  DonoImoveisRoute: DonoImoveisRouteWithChildren,
  DonoManutencaoRoute: DonoManutencaoRoute,
  DonoMapaRoute: DonoMapaRoute,
  DonoPagamentosRoute: DonoPagamentosRoute,
  DonoVisaoGeralRoute: DonoVisaoGeralRoute,
}

const DonoRouteWithChildren = DonoRoute._addFileChildren(DonoRouteChildren)

interface InquilinoRouteChildren {
  InquilinoContratoRoute: typeof InquilinoContratoRoute
  InquilinoConversasRoute: typeof InquilinoConversasRoute
  InquilinoDocumentosRoute: typeof InquilinoDocumentosRoute
  InquilinoFinanceiroRoute: typeof InquilinoFinanceiroRoute
  InquilinoManutencaoRoute: typeof InquilinoManutencaoRoute
  InquilinoMeuImovelRoute: typeof InquilinoMeuImovelRoute
  InquilinoProximidadesRoute: typeof InquilinoProximidadesRoute
  InquilinoVisaoGeralRoute: typeof InquilinoVisaoGeralRoute
}

const InquilinoRouteChildren: InquilinoRouteChildren = {
  InquilinoContratoRoute: InquilinoContratoRoute,
  InquilinoConversasRoute: InquilinoConversasRoute,
  InquilinoDocumentosRoute: InquilinoDocumentosRoute,
  InquilinoFinanceiroRoute: InquilinoFinanceiroRoute,
  InquilinoManutencaoRoute: InquilinoManutencaoRoute,
  InquilinoMeuImovelRoute: InquilinoMeuImovelRoute,
  InquilinoProximidadesRoute: InquilinoProximidadesRoute,
  InquilinoVisaoGeralRoute: InquilinoVisaoGeralRoute,
}

const InquilinoRouteWithChildren = InquilinoRoute._addFileChildren(
  InquilinoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DonoRoute: DonoRouteWithChildren,
  InquilinoRoute: InquilinoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
